title: Illustris Virtual Observatory
description: A reworking and update of the existing sunpy module (now in Python 3), developed by Dr. Paul Torrey (ptorrey@mit.edu) and Dr. Greg Snyder (gsnyder@stsci.edu). Here we offer a streamlined, user-friendly program to produce mock galaxy images from either SDSS or HST. (HST is not 100% operational as including backgrounds does not work as intended).
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
