# Permalinks
permalink:           /:title
relative_permalinks: false
theme: jekyll-theme-cayman

# Setup
timezone:            your timezone # eg. Asia/Kathmandu
locale:              your locale language # eg. en_us
name:				         Illustris Virtual Observatory
title:               Illustris Virtual Observatory
tagline:             'Generate mock SDSS or HST observations of galaxies across cosmic time. Galaxies are from the Illustris simulation and this program is heavily based on the Sunpy module by Dr. Torrey (ptorrey@mit.edu) and Dr. Snyder (gsnyder@stsci.edu).'
description:         'description'
url:                 site url
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 your name
  url:            	 your site url
  facebook:          username
  twitter:           username
  google_plus:       username
  linkedin:          username
  dribbble:          username
  pinterest:         username
  kiva:              username

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
